### ISSUE TITLE
魅族MX2手机底部会有一个底栏，应该是魅族兼容问题

### ISSUE THREAD

**Issue by fighterweb** [maoruibin/AppPlus#1]
![s50928-153728](https://cloud.githubusercontent.com/assets/948119/10130067/70fa6e0a-65f7-11e5-9aee-84d7e020666e.jpg)，另外在设置完主题颜色后返回时偶尔会出现异常自动退出。

**Comment by maoruibin** [comment]
1、你的Flyme是不是基于Android5.0的？
2、奔溃问题 应该是PackageManager那块的问题，暂时没想到好方法！
谢谢反馈！

**Comment by maoruibin** [comment]
奔溃问题已经解决，现在下载最新的 0.3.0版本 应该就好了 
魅族适配问题确实存在，不过不碍事，暂时先这样~

**Comment by fighterweb** [comment]
ok，3q
