### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [maoruibin/AppPlus#4]
Would you consider attaching the `.apk` file with each `release/`, so folks not using GApps on their devices (and thus not using _Google Play Store_) could get it as well? Or is your app tied to _Google Services_ so this wouldn't make sense?

Thanks in advance,
Izzy.

**Comment by maoruibin** [comment]
each release? what's mean ?

**Comment by IzzySoft** [comment]
Sorry for being ambiguous. Of course I didn't mean for "past releases" – but for the latest release available currently, and whenever a new release is made. See [your project's `release/` page](https://github.com/maoruibin/AppPlus/releases) and [Creating releases](https://help.github.com/articles/creating-releases/) in the Github documentation. Minimal efforts – but huge impact :)

**Comment by maoruibin** [comment]
ok  i will do it in next release !

**Comment by IzzySoft** [comment]
Thanks in advance! Could you also do it for the current (last) release to start with?
